version: "3.5"
services:
  elasticsearch:
    networks:
      - otlp
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    networks:
      - otlp
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  prometheus:
    networks:
      - otlp
    image: prom/prometheus:latest
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  jaeger:
    networks:
      - otlp
    image: jaegertracing/all-in-one:latest
    volumes:
      - "./config/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "16686:16686"
    depends_on:
      - prometheus
  otel_collector:
    networks:
      - otlp
    image: otel/opentelemetry-collector-contrib:0.58.0
    volumes:
      - "./config/otel-collector.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    environment:
      - OTEL_LOG_LEVEL=debug
    ports:
      - "4317:4317"
    depends_on:
      - prometheus
      - jaeger
      - elasticsearch
networks:
  otlp:
